import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { BookOpenCheck, Boxes, Building2, ClipboardList, FileBarChart, GraduationCap, LayoutDashboard, LibraryBig, Settings, Upload, Users, UserRoundCog } from "lucide-react";
import { useEffect, useState } from "react";
import { RoleGate } from "@/components/auth/RoleGate";
import { WorkspaceShell, type NavItem } from "@/components/layout/WorkspaceShell";
import { getAdminFoundation } from "@/lib/identity.functions";

export const adminItems: NavItem[] = [
  {label:"Dashboard",to:"/admin",icon:LayoutDashboard},{label:"Alunos",to:"/admin/alunos",icon:GraduationCap},{label:"Professores",to:"/admin/professores",icon:UserRoundCog},{label:"Cursos",to:"/admin/cursos",icon:BookOpenCheck},{label:"Turmas",to:"/admin/turmas",icon:Users},{label:"Módulos",to:"/admin/modulos",icon:Boxes},{label:"Provas",to:"/admin/provas",icon:ClipboardList},{label:"Banco de Questões",to:"/admin/questoes",icon:LibraryBig},{label:"Resultados",to:"/admin/resultados",icon:FileBarChart},{label:"Importações",to:"/admin/importacoes",icon:Upload},{label:"Relatórios",to:"/admin/relatorios",icon:Building2},{label:"Configurações",to:"/admin/configuracoes",icon:Settings},
];
export const Route=createFileRoute("/admin")({head:()=>({meta:[{title:"Administração | Repertório"},{name:"description",content:"Painel administrativo do Repertório."},{property:"og:title",content:"Administração | Repertório"},{property:"og:description",content:"Painel administrativo do Repertório."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:AdminPage});
function AdminPage(){const load=useServerFn(getAdminFoundation);const[data,setData]=useState<{counts:{students:number;teachers:number;classes:number;assessments:number};recent:Array<{id:string;action:string;created_at:string}>}|null>(null);useEffect(()=>{load().then(setData).catch((error)=>console.error("[Admin dashboard]",error));},[load]);const cards=[["Alunos cadastrados",data?.counts.students??"—"],["Professores ativos",data?.counts.teachers??"—"],["Turmas",data?.counts.classes??"—"],["Provas",data?.counts.assessments??"—"]];return <RoleGate allow={["admin"]}><WorkspaceShell area="Administração" items={adminItems}><div><p className="text-xs font-semibold uppercase text-muted-foreground">Visão geral</p><h1 className="mt-2 font-display text-4xl font-semibold">Dashboard administrativo</h1><p className="mt-2 text-muted-foreground">Acompanhe a fundação e os cadastros essenciais da escola.</p></div><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value])=><section key={label} className="rounded-lg border bg-card p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 font-display text-4xl font-semibold">{value}</p></section>)}</div><div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-lg border bg-card p-6"><h2 className="font-display text-xl font-semibold">Avaliações recentes</h2><p className="mt-5 text-sm text-muted-foreground">Nenhuma avaliação criada.</p></section><section className="rounded-lg border bg-card p-6"><h2 className="font-display text-xl font-semibold">Atividades administrativas recentes</h2>{data?.recent.length?<ul className="mt-4 space-y-3">{data.recent.map((item)=><li key={item.id} className="border-b pb-3 text-sm"><span className="font-medium">{item.action}</span><span className="block text-xs text-muted-foreground">{new Date(item.created_at).toLocaleString("pt-BR")}</span></li>)}</ul>:<p className="mt-5 text-sm text-muted-foreground">Nenhuma atividade registrada.</p>}</section></div></WorkspaceShell></RoleGate>}