import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { Eye, EyeOff, Loader2, LogIn, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { useAuth, destinationForRole } from "@/auth/AuthContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export const Route = createFileRoute("/login")({ head: () => ({ meta: [{ title: "Login da equipe | Repertório" },{ name: "description", content: "Acesso seguro para administradores e professores do Repertório." },{ property: "og:title", content: "Login da equipe | Repertório" },{ property: "og:description", content: "Acesso seguro para administradores e professores do Repertório." },{ property: "og:type", content: "website" },{ name: "twitter:card", content: "summary" }] }), component: LoginPage });

function LoginPage() {
  const auth = useAuth(); const navigate = useNavigate();
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [show,setShow]=useState(false); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState("");
  useEffect(() => { if (!auth.loading && auth.isAuthenticated && auth.role) void navigate({ to: destinationForRole(auth.role), replace: true }); }, [auth.loading,auth.isAuthenticated,auth.role,navigate]);
  async function submit(event: React.FormEvent) { event.preventDefault(); setSubmitting(true); setError(""); const result=await auth.signIn(email,password); setSubmitting(false); if (!result.ok) { const messages={ credentials:"E-mail ou senha inválidos.", unconfirmed:"Confirme seu e-mail antes de entrar.", configuration:"Sua conta ainda não está configurada corretamente. Procure um administrador.", connection:"Não foi possível conectar ao sistema. Tente novamente." }; setError(messages[result.kind]); return; } await navigate({ to: destinationForRole(result.role), replace:true }); }
  return <main className="grid min-h-screen place-items-center bg-background px-5 py-10"><section className="w-full max-w-md"><div className="mb-8 flex items-center justify-center gap-3"><span className="grid size-11 place-items-center rounded-lg bg-primary font-display text-xl font-semibold text-primary-foreground">R</span><div><h1 className="font-display text-xl font-semibold">Repertório</h1><p className="text-xs text-muted-foreground">Acesso da equipe</p></div></div><div className="rounded-lg border bg-card p-6 shadow-sm sm:p-8"><ShieldCheck className="size-10 text-primary"/><h2 className="mt-5 font-display text-3xl font-semibold">Entre na sua conta</h2><p className="mt-2 text-sm text-muted-foreground">Administradores e professores usam este acesso.</p><form className="mt-7 space-y-4" onSubmit={submit}><div className="space-y-2"><Label htmlFor="email">E-mail</Label><Input id="email" type="email" autoComplete="email" value={email} onChange={(e)=>setEmail(e.target.value)} required className="h-12 bg-background"/></div><div className="space-y-2"><Label htmlFor="password">Senha</Label><div className="relative"><Input id="password" type={show?"text":"password"} autoComplete="current-password" value={password} onChange={(e)=>setPassword(e.target.value)} required className="h-12 bg-background pr-12"/><Button type="button" variant="ghost" size="icon" className="absolute right-1.5 top-1.5" aria-label={show?"Ocultar senha":"Mostrar senha"} onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</Button></div></div>{error&&<p role="alert" className="rounded-md bg-destructive/10 px-3 py-2 text-sm text-destructive">{error}</p>}<Button type="submit" className="h-12 w-full" disabled={submitting}>{submitting?<Loader2 className="animate-spin"/>:<LogIn/>} ENTRAR</Button></form><Button asChild variant="link" className="mt-3 w-full"><Link to="/forgot-password">Esqueci minha senha</Link></Button></div><p className="mt-5 text-center text-sm text-muted-foreground">Primeira instalação? <Link to="/setup" className="font-semibold text-primary underline">Configuração Inicial</Link></p></section></main>;
}